package PDFModule;

/**
 * PDFModule/_PDFProcessorStub.java
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from PDFProcessor.idl
 * Corrected for Java 11+ compatibility
 */
public class _PDFProcessorStub extends org.omg.CORBA.portable.ObjectImpl
        implements PDFModule.PDFProcessor {

    private static final String[] __ids = {
        "IDL:PDFModule/PDFProcessor:1.0"
    };

    @Override
    public String[] _ids() {
        return __ids.clone();
    }

    // -----------------------------------------------------------------------
    // mergePDFs
    // -----------------------------------------------------------------------
    public byte[] mergePDFs(byte[][] pdfFiles) throws PDFModule.PDFException {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("mergePDFs", true);
            PDFModule.PDFListHelper.write($out, pdfFiles);
            $in = _invoke($out);
            byte[] $result = PDFModule.PDFDataHelper.read($in);
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            if (_id.equals("IDL:PDFModule/PDFException:1.0"))
                throw PDFModule.PDFExceptionHelper.read($in);
            else
                throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return mergePDFs(pdfFiles);
        } finally {
            _releaseReply($in);
        }
    } // mergePDFs

    // -----------------------------------------------------------------------
    // splitPDF
    // -----------------------------------------------------------------------
    public byte[][] splitPDF(byte[] pdfFile, int pagesPerChunk) throws PDFModule.PDFException {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("splitPDF", true);
            PDFModule.PDFDataHelper.write($out, pdfFile);
            $out.write_long(pagesPerChunk);
            $in = _invoke($out);
            byte[][] $result = PDFModule.PDFListHelper.read($in);
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            if (_id.equals("IDL:PDFModule/PDFException:1.0"))
                throw PDFModule.PDFExceptionHelper.read($in);
            else
                throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return splitPDF(pdfFile, pagesPerChunk);
        } finally {
            _releaseReply($in);
        }
    } // splitPDF

    // -----------------------------------------------------------------------
    // extractPages
    // -----------------------------------------------------------------------
    public byte[] extractPages(byte[] pdfFile, int[] pages)
            throws PDFModule.PDFException, PDFModule.PageNotFoundException {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("extractPages", true);
            PDFModule.PDFDataHelper.write($out, pdfFile);
            PDFModule.PageListHelper.write($out, pages);
            $in = _invoke($out);
            byte[] $result = PDFModule.PDFDataHelper.read($in);
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            if (_id.equals("IDL:PDFModule/PDFException:1.0"))
                throw PDFModule.PDFExceptionHelper.read($in);
            else if (_id.equals("IDL:PDFModule/PageNotFoundException:1.0"))
                throw PDFModule.PageNotFoundExceptionHelper.read($in);
            else
                throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return extractPages(pdfFile, pages);
        } finally {
            _releaseReply($in);
        }
    } // extractPages

    // -----------------------------------------------------------------------
    // deletePages
    // -----------------------------------------------------------------------
    public byte[] deletePages(byte[] pdfFile, int[] pages)
            throws PDFModule.PDFException, PDFModule.PageNotFoundException {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("deletePages", true);
            PDFModule.PDFDataHelper.write($out, pdfFile);
            PDFModule.PageListHelper.write($out, pages);
            $in = _invoke($out);
            byte[] $result = PDFModule.PDFDataHelper.read($in);
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            if (_id.equals("IDL:PDFModule/PDFException:1.0"))
                throw PDFModule.PDFExceptionHelper.read($in);
            else if (_id.equals("IDL:PDFModule/PageNotFoundException:1.0"))
                throw PDFModule.PageNotFoundExceptionHelper.read($in);
            else
                throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return deletePages(pdfFile, pages);
        } finally {
            _releaseReply($in);
        }
    } // deletePages

    // -----------------------------------------------------------------------
    // addPassword
    // -----------------------------------------------------------------------
    public byte[] addPassword(byte[] pdfFile, String ownerPwd, String userPwd)
            throws PDFModule.PDFException, PDFModule.InvalidPasswordException {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("addPassword", true);
            PDFModule.PDFDataHelper.write($out, pdfFile);
            $out.write_string(ownerPwd);
            $out.write_string(userPwd);
            $in = _invoke($out);
            byte[] $result = PDFModule.PDFDataHelper.read($in);
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            if (_id.equals("IDL:PDFModule/PDFException:1.0"))
                throw PDFModule.PDFExceptionHelper.read($in);
            else if (_id.equals("IDL:PDFModule/InvalidPasswordException:1.0"))
                throw PDFModule.InvalidPasswordExceptionHelper.read($in);
            else
                throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return addPassword(pdfFile, ownerPwd, userPwd);
        } finally {
            _releaseReply($in);
        }
    } // addPassword

    // -----------------------------------------------------------------------
    // convertToImages  (retourne String[], prend int dpi)
    // -----------------------------------------------------------------------
    public String[] convertToImages(byte[] pdfFile, String format, int dpi)
            throws PDFModule.PDFException, PDFModule.ConversionException {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("convertToImages", true);
            PDFModule.PDFDataHelper.write($out, pdfFile);
            $out.write_string(format);
            $out.write_long(dpi);
            $in = _invoke($out);
            int $len = $in.read_long();
            String[] $result = new String[$len];
            for (int $i = 0; $i < $len; $i++) {
                $result[$i] = $in.read_string();
            }
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            if (_id.equals("IDL:PDFModule/PDFException:1.0"))
                throw PDFModule.PDFExceptionHelper.read($in);
            else if (_id.equals("IDL:PDFModule/ConversionException:1.0"))
                throw PDFModule.ConversionExceptionHelper.read($in);
            else
                throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return convertToImages(pdfFile, format, dpi);
        } finally {
            _releaseReply($in);
        }
    } // convertToImages

    // -----------------------------------------------------------------------
    // extractText
    // -----------------------------------------------------------------------
    public String extractText(byte[] pdfFile) throws PDFModule.PDFException {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("extractText", true);
            PDFModule.PDFDataHelper.write($out, pdfFile);
            $in = _invoke($out);
            String $result = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            if (_id.equals("IDL:PDFModule/PDFException:1.0"))
                throw PDFModule.PDFExceptionHelper.read($in);
            else
                throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return extractText(pdfFile);
        } finally {
            _releaseReply($in);
        }
    } // extractText

    // -----------------------------------------------------------------------
    // createPDF
    // -----------------------------------------------------------------------
    public byte[] createPDF(String title, String content, String author)
            throws PDFModule.PDFException {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("createPDF", true);
            $out.write_string(title);
            $out.write_string(content);
            $out.write_string(author);
            $in = _invoke($out);
            byte[] $result = PDFModule.PDFDataHelper.read($in);
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            if (_id.equals("IDL:PDFModule/PDFException:1.0"))
                throw PDFModule.PDFExceptionHelper.read($in);
            else
                throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return createPDF(title, content, author);
        } finally {
            _releaseReply($in);
        }
    } // createPDF

    // -----------------------------------------------------------------------
    // getPageCount
    // -----------------------------------------------------------------------
    public int getPageCount(byte[] pdfFile) throws PDFModule.PDFException {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("getPageCount", true);
            PDFModule.PDFDataHelper.write($out, pdfFile);
            $in = _invoke($out);
            int $result = $in.read_long();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            if (_id.equals("IDL:PDFModule/PDFException:1.0"))
                throw PDFModule.PDFExceptionHelper.read($in);
            else
                throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return getPageCount(pdfFile);
        } finally {
            _releaseReply($in);
        }
    } // getPageCount

    // -----------------------------------------------------------------------
    // ping
    // -----------------------------------------------------------------------
    public boolean ping() {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("ping", true);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            throw new org.omg.CORBA.MARSHAL($ex.getId());
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return ping();
        } finally {
            _releaseReply($in);
        }
    } // ping

} // class _PDFProcessorStub
