package PDFModule;


/**
* PDFModule/ConversionException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFProcessor.idl
* Saturday, May 16, 2026 1:09:38 PM GMT
*/

public final class ConversionException extends org.omg.CORBA.UserException
{
  public String message = null;

  public ConversionException ()
  {
    super(ConversionExceptionHelper.id());
  } // ctor

  public ConversionException (String _message)
  {
    super(ConversionExceptionHelper.id());
    message = _message;
  } // ctor


  public ConversionException (String $reason, String _message)
  {
    super(ConversionExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class ConversionException
