package PDFModule;


/**
* PDFModule/ImageListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFProcessor.idl
* Saturday, May 16, 2026 1:09:38 PM GMT
*/

public final class ImageListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ImageListHolder ()
  {
  }

  public ImageListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFModule.ImageListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFModule.ImageListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFModule.ImageListHelper.type ();
  }

}
