package PDFModule;


/**
* PDFModule/InvalidPasswordException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFProcessor.idl
* Saturday, May 16, 2026 1:09:38 PM GMT
*/

public final class InvalidPasswordException extends org.omg.CORBA.UserException
{
  public String message = null;

  public InvalidPasswordException ()
  {
    super(InvalidPasswordExceptionHelper.id());
  } // ctor

  public InvalidPasswordException (String _message)
  {
    super(InvalidPasswordExceptionHelper.id());
    message = _message;
  } // ctor


  public InvalidPasswordException (String $reason, String _message)
  {
    super(InvalidPasswordExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class InvalidPasswordException
