package PDFModule;


/**
* PDFModule/PageListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFProcessor.idl
* Saturday, May 16, 2026 1:09:38 PM GMT
*/

public final class PageListHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public PageListHolder ()
  {
  }

  public PageListHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFModule.PageListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFModule.PageListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFModule.PageListHelper.type ();
  }

}
