package PDFModule;

/**
* PDFModule/PageNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFProcessor.idl
* Saturday, May 16, 2026 1:09:38 PM GMT
*/

public final class PageNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFModule.PageNotFoundException value = null;

  public PageNotFoundExceptionHolder ()
  {
  }

  public PageNotFoundExceptionHolder (PDFModule.PageNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFModule.PageNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFModule.PageNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFModule.PageNotFoundExceptionHelper.type ();
  }

}
