package PDFModule;


/**
* PDFModule/PDFDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFProcessor.idl
* Saturday, May 16, 2026 1:09:38 PM GMT
*/

public final class PDFDataHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public PDFDataHolder ()
  {
  }

  public PDFDataHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFModule.PDFDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFModule.PDFDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFModule.PDFDataHelper.type ();
  }

}
