package PDFModule;


/**
* PDFModule/PDFListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFProcessor.idl
* Saturday, May 16, 2026 1:09:38 PM GMT
*/

public final class PDFListHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[][] = null;

  public PDFListHolder ()
  {
  }

  public PDFListHolder (byte[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFModule.PDFListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFModule.PDFListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFModule.PDFListHelper.type ();
  }

}
