package PDFModule;


/**
* PDFModule/PDFProcessorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Sunday, May 10, 2026 4:32:50 PM GMT
*/

abstract public class PDFProcessorHelper
{
  private static String  _id = "IDL:PDFModule/PDFProcessor:1.0";

  public static void insert (org.omg.CORBA.Any a, PDFModule.PDFProcessor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PDFModule.PDFProcessor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PDFModule.PDFProcessorHelper.id (), "PDFProcessor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PDFModule.PDFProcessor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PDFProcessorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PDFModule.PDFProcessor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PDFModule.PDFProcessor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PDFModule.PDFProcessor)
      return (PDFModule.PDFProcessor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PDFModule._PDFProcessorStub stub = new PDFModule._PDFProcessorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PDFModule.PDFProcessor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PDFModule.PDFProcessor)
      return (PDFModule.PDFProcessor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PDFModule._PDFProcessorStub stub = new PDFModule._PDFProcessorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
