package PDFModule;


/**
* PDFModule/PDFProcessorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Sunday, May 10, 2026 4:32:50 PM GMT
*/

public interface PDFProcessorOperations 
{
  String extractText (String filePath);
  boolean protectPDF (String filePath, String password);
} // interface PDFProcessorOperations
