package PDFModule;

/**
* PDFModule/PDFProcessorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Sunday, May 10, 2026 4:32:50 PM GMT
*/

public final class PDFProcessorHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFModule.PDFProcessor value = null;

  public PDFProcessorHolder ()
  {
  }

  public PDFProcessorHolder (PDFModule.PDFProcessor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFModule.PDFProcessorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFModule.PDFProcessorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFModule.PDFProcessorHelper.type ();
  }

}
