package PDFModule;


/**
* PDFModule/PDFProcessor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Sunday, May 10, 2026 4:32:50 PM GMT
*/

public interface PDFProcessor extends PDFProcessorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PDFProcessor
