package PDFModule;

/**
* PDFModule/ConversionExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFProcessor.idl
* Saturday, May 16, 2026 1:09:38 PM GMT
*/

public final class ConversionExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFModule.ConversionException value = null;

  public ConversionExceptionHolder ()
  {
  }

  public ConversionExceptionHolder (PDFModule.ConversionException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFModule.ConversionExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFModule.ConversionExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFModule.ConversionExceptionHelper.type ();
  }

}
