package PDFModule;


/**
* PDFModule/PageNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFProcessor.idl
* Saturday, May 16, 2026 1:09:38 PM GMT
*/

public final class PageNotFoundException extends org.omg.CORBA.UserException
{
  public String message = null;
  public int pageNumber = (int)0;

  public PageNotFoundException ()
  {
    super(PageNotFoundExceptionHelper.id());
  } // ctor

  public PageNotFoundException (String _message, int _pageNumber)
  {
    super(PageNotFoundExceptionHelper.id());
    message = _message;
    pageNumber = _pageNumber;
  } // ctor


  public PageNotFoundException (String $reason, String _message, int _pageNumber)
  {
    super(PageNotFoundExceptionHelper.id() + "  " + $reason);
    message = _message;
    pageNumber = _pageNumber;
  } // ctor

} // class PageNotFoundException
