package PDFModule;

/**
* PDFModule/PDFExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFProcessor.idl
* Saturday, May 16, 2026 1:09:38 PM GMT
*/

public final class PDFExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFModule.PDFException value = null;

  public PDFExceptionHolder ()
  {
  }

  public PDFExceptionHolder (PDFModule.PDFException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFModule.PDFExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFModule.PDFExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFModule.PDFExceptionHelper.type ();
  }

}
