package PDFModule;


/**
* PDFModule/PDFException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFProcessor.idl
* Saturday, May 16, 2026 1:09:38 PM GMT
*/

public final class PDFException extends org.omg.CORBA.UserException
{
  public String message = null;
  public int code = (int)0;

  public PDFException ()
  {
    super(PDFExceptionHelper.id());
  } // ctor

  public PDFException (String _message, int _code)
  {
    super(PDFExceptionHelper.id());
    message = _message;
    code = _code;
  } // ctor


  public PDFException (String $reason, String _message, int _code)
  {
    super(PDFExceptionHelper.id() + "  " + $reason);
    message = _message;
    code = _code;
  } // ctor

} // class PDFException
