package PDFModule;


/**
* PDFModule/PDFProcessorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFProcessor.idl
* Saturday, May 16, 2026 1:09:38 PM GMT
*/

public interface PDFProcessorOperations 
{
  byte[] mergePDFs (byte[][] pdfFiles) throws PDFModule.PDFException;
  byte[][] splitPDF (byte[] pdfFile, int pagesPerChunk) throws PDFModule.PDFException;
  byte[] extractPages (byte[] pdfFile, int[] pages) throws PDFModule.PDFException, PDFModule.PageNotFoundException;
  byte[] deletePages (byte[] pdfFile, int[] pages) throws PDFModule.PDFException, PDFModule.PageNotFoundException;
  byte[] addPassword (byte[] pdfFile, String ownerPwd, String userPwd) throws PDFModule.PDFException, PDFModule.InvalidPasswordException;
  String[] convertToImages (byte[] pdfFile, String format, int dpi) throws PDFModule.PDFException, PDFModule.ConversionException;
  String extractText (byte[] pdfFile) throws PDFModule.PDFException;
  byte[] createPDF (String title, String content, String author) throws PDFModule.PDFException;
  int getPageCount (byte[] pdfFile) throws PDFModule.PDFException;
  boolean ping ();
} // interface PDFProcessorOperations
