package PDFModule;


/**
* PDFModule/PDFProcessorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFProcessor.idl
* Saturday, May 16, 2026 1:09:38 PM GMT
*/

public abstract class PDFProcessorPOA extends org.omg.PortableServer.Servant
 implements PDFModule.PDFProcessorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("mergePDFs", new java.lang.Integer (0));
    _methods.put ("splitPDF", new java.lang.Integer (1));
    _methods.put ("extractPages", new java.lang.Integer (2));
    _methods.put ("deletePages", new java.lang.Integer (3));
    _methods.put ("addPassword", new java.lang.Integer (4));
    _methods.put ("convertToImages", new java.lang.Integer (5));
    _methods.put ("extractText", new java.lang.Integer (6));
    _methods.put ("createPDF", new java.lang.Integer (7));
    _methods.put ("getPageCount", new java.lang.Integer (8));
    _methods.put ("ping", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PDFModule/PDFProcessor/mergePDFs
       {
         try {
           byte pdfFiles[][] = PDFModule.PDFListHelper.read (in);
           byte $result[] = null;
           $result = this.mergePDFs (pdfFiles);
           out = $rh.createReply();
           PDFModule.PDFDataHelper.write (out, $result);
         } catch (PDFModule.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFModule.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // PDFModule/PDFProcessor/splitPDF
       {
         try {
           byte pdfFile[] = PDFModule.PDFDataHelper.read (in);
           int pagesPerChunk = in.read_long ();
           byte $result[][] = null;
           $result = this.splitPDF (pdfFile, pagesPerChunk);
           out = $rh.createReply();
           PDFModule.PDFListHelper.write (out, $result);
         } catch (PDFModule.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFModule.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // PDFModule/PDFProcessor/extractPages
       {
         try {
           byte pdfFile[] = PDFModule.PDFDataHelper.read (in);
           int pages[] = PDFModule.PageListHelper.read (in);
           byte $result[] = null;
           $result = this.extractPages (pdfFile, pages);
           out = $rh.createReply();
           PDFModule.PDFDataHelper.write (out, $result);
         } catch (PDFModule.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFModule.PDFExceptionHelper.write (out, $ex);
         } catch (PDFModule.PageNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           PDFModule.PageNotFoundExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // PDFModule/PDFProcessor/deletePages
       {
         try {
           byte pdfFile[] = PDFModule.PDFDataHelper.read (in);
           int pages[] = PDFModule.PageListHelper.read (in);
           byte $result[] = null;
           $result = this.deletePages (pdfFile, pages);
           out = $rh.createReply();
           PDFModule.PDFDataHelper.write (out, $result);
         } catch (PDFModule.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFModule.PDFExceptionHelper.write (out, $ex);
         } catch (PDFModule.PageNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           PDFModule.PageNotFoundExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // PDFModule/PDFProcessor/addPassword
       {
         try {
           byte pdfFile[] = PDFModule.PDFDataHelper.read (in);
           String ownerPwd = in.read_string ();
           String userPwd = in.read_string ();
           byte $result[] = null;
           $result = this.addPassword (pdfFile, ownerPwd, userPwd);
           out = $rh.createReply();
           PDFModule.PDFDataHelper.write (out, $result);
         } catch (PDFModule.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFModule.PDFExceptionHelper.write (out, $ex);
         } catch (PDFModule.InvalidPasswordException $ex) {
           out = $rh.createExceptionReply ();
           PDFModule.InvalidPasswordExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // PDFModule/PDFProcessor/convertToImages
       {
         try {
           byte pdfFile[] = PDFModule.PDFDataHelper.read (in);
           String format = in.read_string ();
           int dpi = in.read_long ();
           String $result[] = null;
           $result = this.convertToImages (pdfFile, format, dpi);
           out = $rh.createReply();
           PDFModule.ImageListHelper.write (out, $result);
         } catch (PDFModule.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFModule.PDFExceptionHelper.write (out, $ex);
         } catch (PDFModule.ConversionException $ex) {
           out = $rh.createExceptionReply ();
           PDFModule.ConversionExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 6:  // PDFModule/PDFProcessor/extractText
       {
         try {
           byte pdfFile[] = PDFModule.PDFDataHelper.read (in);
           String $result = null;
           $result = this.extractText (pdfFile);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (PDFModule.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFModule.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 7:  // PDFModule/PDFProcessor/createPDF
       {
         try {
           String title = in.read_string ();
           String content = in.read_string ();
           String author = in.read_string ();
           byte $result[] = null;
           $result = this.createPDF (title, content, author);
           out = $rh.createReply();
           PDFModule.PDFDataHelper.write (out, $result);
         } catch (PDFModule.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFModule.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 8:  // PDFModule/PDFProcessor/getPageCount
       {
         try {
           byte pdfFile[] = PDFModule.PDFDataHelper.read (in);
           int $result = (int)0;
           $result = this.getPageCount (pdfFile);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (PDFModule.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFModule.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 9:  // PDFModule/PDFProcessor/ping
       {
         boolean $result = false;
         $result = this.ping ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PDFModule/PDFProcessor:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PDFProcessor _this() 
  {
    return PDFProcessorHelper.narrow(
    super._this_object());
  }

  public PDFProcessor _this(org.omg.CORBA.ORB orb) 
  {
    return PDFProcessorHelper.narrow(
    super._this_object(orb));
  }


} // class PDFProcessorPOA
