# ── Serveur ──────────────────────────────────────────────────
server.port=8085
spring.application.name=pdf-gateway

# ── CORBA ────────────────────────────────────────────────────
corba.host=localhost
corba.port=1050
corba.ior.path=/app/PDFProcessor.ior

# ── Upload fichiers ──────────────────────────────────────────
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ── Actuator ─────────────────────────────────────────────────
management.endpoints.web.exposure.include=health,mappings,info
management.endpoint.health.show-details=always

# ── Logs ─────────────────────────────────────────────────────
logging.level.com.example.gateway=INFO
logging.level.root=WARN
