server.port=8085
spring.application.name=pdf-gateway
corba.host=localhost
corba.port=1050
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
management.endpoints.web.exposure.include=health,mappings,info
management.endpoint.health.show-details=always
logging.level.com.example.gateway=INFO
